### ISSUE TITLE
Unable to apply light theme

### ISSUE THREAD

**Issue by manjunathc23** [negusoft/GreenMatter#1]
This lib doesn't allow me to apply light theme. Please fix it! By default its non - light theme, App background becomes grey'ish.

**Comment by manjunathc23** [comment]
@blurkidi : for visibility

**Comment by manjunathc23** [comment]
So the light theme is available for us?

**Comment by Ivolian** [comment]
+1

**Comment by blurkidi** [comment]
The light theme is now available in the 'dev' branch. It will be included in the next release.
