### ISSUE TITLE
Exception raised during rendering: Color value 

### ISSUE THREAD

**Issue by syedalinaqi** [negusoft/GreenMatter#9]
This Error Occurred I Couldn't See The Device Preview.

Exception raised during rendering: Color value 'D:\Android_Development\Android_Projects\New_Android_Projects\WebsiteInformer\app\build\intermediates\exploded-aar\com.negusoft.greenmatter\GreenMatter\0.7-alpha\res\color\gm__primary_dark.xml' must start with #

**Comment by Ivolian** [comment]
me too

**Comment by syedalinaqi** [comment]
After messing around with the library i found the solution to my problem...
